---

# See https://github.com/elastic/elasticsearch/issues/85876
# for more information why this is needed

- name: Workaround for EL > 8
  block:

    - name: Show a warning
      debug:
        msg: "For this workaround to work, please set elastic_rpm_workaround to true"
      when:
        - not elastic_rpm_workaround | bool

    - name: Set Crypto policies to legacy
      command: "update-crypto-policies --set LEGACY"
      when:
        - elastic_rpm_workaround | bool
  when:
    - ansible_distribution_major_version >= "9"

- name: Ensure Elastic repository key is available (RedHat)
  ansible.builtin.rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Ensure Elastic Stack yum repository is configured (RedHat)
  ansible.builtin.yum_repository:
    name: elastic-{{ elastic_release }}.x
    description: Elastic Release {{ elastic_release }}.x
    file: elastic-release
    baseurl: https://artifacts.elastic.co/packages/{{ elastic_release }}.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: elastic_variant == "elastic"

- name: Ensure Elastic Stack OSS yum repository is configured (RedHat)
  ansible.builtin.yum_repository:
    name: elastic-oss-{{ elastic_release }}.x
    description: Elastic OSS Release {{ elastic_release }}.x
    file: elastic-oss-release
    baseurl: https://artifacts.elastic.co/packages/oss-{{ elastic_release }}.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: elastic_variant == "oss"
